[versions]
agp               = "8.13.2"
kotlin            = "2.2.21"
coreKtx           = "1.17.0"
activityCompose   = "1.12.1"
lifecycle         = "2.10.0"
composeBom        = "2025.12.00"
coroutines        = "1.10.2"
serializationJson = "1.9.0"
junit             = "4.13.2"
androidxJunit     = "1.3.0"
espresso          = "3.7.0"
gradleVersions    = "0.51.0"
coreSplashScreen  = "1.0.1"

[libraries]
androidx-core-ktx                        = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-activity-compose                = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-lifecycle-runtime-ktx           = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel-ktx         = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel-compose     = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycle" }
androidx-compose-bom                     = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui                      = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics             = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling              = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview      = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-test-junit4          = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-ui-test-manifest        = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-foundation              = { group = "androidx.compose.foundation", name = "foundation" }
androidx-compose-material3               = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended" }
kotlinx-coroutines-core                  = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-android               = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }
kotlinx-serialization-json               = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "serializationJson" }
junit                                    = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit                           = { group = "androidx.test.ext", name = "junit", version.ref = "androidxJunit" }
androidx-espresso-core                   = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso" }
androidx-core-splashscreen               = { group = "androidx.core", name = "core-splashscreen", version.ref = "coreSplashScreen" }

[plugins]
android-application  = { id = "com.android.application", version.ref = "agp" }
kotlin-android       = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose       = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
gradle-versions      = { id = "com.github.ben-manes.versions", version.ref = "gradleVersions" }
ktfmt                = { id = "com.ncorti.ktfmt.gradle", version = "0.25.0" }
